#' Metaboanalyst_code_pairwise_analysis_CSCJ.R
#' This piece of code is generated by MetaboAnalyst (http://metaboanalyst.ca) ver 4.0 when a pairwise comaprison of two species CJ and CS was performed. The code conatins the parameters that were used within MetaboAnalyst to generate the volcano plot and the fold change table Volcanoplot_Metaboanalyst_CSCJ.csv.
#' 
#' @author Purva Kulkarni                                                   

mSet<-InitDataObjects("pktable", "stat", FALSE)
mSet<-Read.TextData(mSet, "Replacing_with_your_file_path", "colu", "disc");
mSet<-SanityCheckData(mSet)
mSet<-ReplaceMin(mSet);
mSet<-Normalization(mSet, "MedianNorm", "LogNorm", "AutoNorm", "CJ2_1", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)
mSet<-Volcano.Anal(mSet, FALSE, 2.0, 0, 0.75,F, 0.1, TRUE, "raw")
mSet<-PlotVolcano(mSet, "volcano_0_", "png", 72, width=NA)
